import { Chatbot, ChatbotVersion } from './types'

export const DEFAULT_CHATBOT_CONFIG: Partial<Chatbot> = {
  name: '',
  website: '',
  description: '',
  apiEndpoint: '',
  apiAuthType: 'none',
  apiAuthValue: '',
  primaryColor: '#3b82f6',
  fontFamily: 'Inter',
  fontSize: '14px',
  fontColor: '#000000',
  borderColor: '#e5e7eb',
  borderWidth: '1px',
  borderRadius: '8px',
  bubbleBorderColor: '#e5e7eb',
  bubbleBorderWidth: '1px',
  bubbleBorderRadius: '8px',
  bubblePadding: '12px',
  userMessageBackgroundColor: '#3b82f6',
  botMessageBackgroundColor: '#f3f4f6',
  showMessageName: false,
  messageName: '',
  messageNamePosition: 'top-of-message',
  showMessageAvatar: true,
  messageBoxColor: '#ffffff',
  shadowColor: '#000000',
  shadowBlur: '4px',
  conversationOpener: 'Hello! How can I help you today?',
  followUpQuestions: [],
  enableFileUpload: false,
  showCitations: true,
  deploymentType: 'popover',
  widgetAvatarStyle: 'circle',
  widgetPosition: 'bottom-right',
  widgetSize: '60px',
  widgetBackgroundColor: '#3b82f6',
  widgetBorderColor: '#ffffff',
  widgetBorderWidth: '2px',
  widgetBorderRadius: '50%',
  widgetShadowColor: '#000000',
  widgetShadowBlur: '8px',
  widgetLabelText: 'Chat',
  widgetLabelColor: '#ffffff',
  widgetAnimation: 'fade',
  widgetAutoShow: true,
  widgetAutoShowDelay: 0,
  widgetOffsetX: '20px',
  widgetOffsetY: '20px',
  widgetZIndex: 9999,
  showNotificationBadge: false,
  notificationBadgeColor: '#ef4444',
  chatWindowWidth: '380px',
  chatWindowHeight: '600px',
  chatWindowBorderColor: '#e5e7eb',
  chatWindowBorderWidth: '1px',
  chatWindowBorderRadius: '8px',
  chatWindowShadowColor: '#000000',
  chatWindowShadowBlur: '4px',
  typingIndicatorStyle: 'spinner',
  typingIndicatorColor: '#6b7280',
  headerTitle: '',
  headerDescription: '',
  headerLogo: '',
  headerBgColor: '#3b82f6',
  headerFontColor: '#ffffff',
  headerFontFamily: 'Inter',
  headerShowAvatar: true,
  headerBorderEnabled: true,
  headerBorderColor: '#e5e7eb',
  headerPaddingX: '16px',
  headerPaddingY: '16px',
  footerBgColor: '#ffffff',
  footerBorderColor: '#e5e7eb',
  footerBorderWidth: '1px',
  footerBorderRadius: '0px',
  footerPaddingX: '16px',
  footerPaddingY: '16px',
  footerInputBgColor: '#ffffff',
  footerInputBorderColor: '#e5e7eb',
  footerInputBorderWidth: '1px',
  footerInputBorderRadius: '8px',
  footerInputFontColor: '#000000',
  sendButtonIcon: 'Send',
  sendButtonRounded: false,
  sendButtonBgColor: '#3b82f6',
  sendButtonIconColor: '#ffffff',
  sendButtonShadowColor: '#000000',
  sendButtonShadowBlur: '0px',
  fileUploadLayout: 'attach-first',
  avatarType: 'icon',
  avatarIcon: 'Bot',
  avatarIconColor: '#ffffff',
  avatarBackgroundColor: '#3b82f6',
  avatarImageUrl: '',
  isPublished: false,
  currentVersion: '1.0.0'
}

export function createDefaultChatbot(name: string): Chatbot {
  return {
    id: `chatbot-${Date.now()}`,
    name: name,
    website: '',
    description: '',
    apiEndpoint: '',
    apiAuthType: 'none',
    apiAuthValue: '',
    logo: '',
    primaryColor: '#3b82f6',
    fontFamily: 'Inter',
    fontSize: '14px',
    fontColor: '#000000',
    borderColor: '#e5e7eb',
    borderWidth: '1px',
    borderRadius: '8px',
    bubbleBorderColor: '#e5e7eb',
    bubbleBorderWidth: '1px',
    bubbleBorderRadius: '8px',
    bubblePadding: '12px',
    userMessageBackgroundColor: '#3b82f6',
    botMessageBackgroundColor: '#f3f4f6',
    showMessageName: false,
    messageName: '',
    messageNamePosition: 'top-of-message',
    showMessageAvatar: true,
    messageBoxColor: '#ffffff',
    shadowColor: '#000000',
    shadowBlur: '4px',
    conversationOpener: 'Hello! How can I help you today?',
    followUpQuestions: [],
    enableFileUpload: false,
    showCitations: true,
    deploymentType: 'popover',
    widgetAvatarStyle: 'circle',
    widgetPosition: 'bottom-right',
    widgetSize: '60px',
    widgetBackgroundColor: '#3b82f6',
    widgetBorderColor: '#ffffff',
    widgetBorderWidth: '2px',
    widgetBorderRadius: '50%',
    widgetShadowColor: '#000000',
    widgetShadowBlur: '8px',
    widgetLabelText: 'Chat',
    widgetLabelColor: '#ffffff',
    widgetAnimation: 'fade',
    widgetAutoShow: true,
    widgetAutoShowDelay: 0,
    widgetOffsetX: '20px',
    widgetOffsetY: '20px',
    widgetZIndex: 9999,
    showNotificationBadge: false,
    notificationBadgeColor: '#ef4444',
    chatWindowWidth: '380px',
    chatWindowHeight: '600px',
    chatWindowBorderColor: '#e5e7eb',
    chatWindowBorderWidth: '1px',
    chatWindowBorderRadius: '8px',
    chatWindowShadowColor: '#000000',
    chatWindowShadowBlur: '4px',
    isPublished: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    versions: [{
      id: `version-${Date.now()}`,
      version: '1.0.0',
      createdAt: new Date(),
      createdBy: 'current-user',
      isPublished: false
    }],
    currentVersion: '1.0.0'
  }
}

export function createDefaultVersion(): ChatbotVersion {
  return {
    id: `version-${Date.now()}`,
    version: '1.0.0',
    createdAt: new Date(),
    createdBy: 'current-user',
    isPublished: false
  }
}

